server:
  port: 28080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/StrayAnimalRescue?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect  # 明确指定 MySQL 方言
    show-sql: true  # 可选，开启 SQL 输出，调试时有帮助
    ddl-auto: update  # 可选，自动更新数据库模式

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.seckill_backend.model
  configuration:
    map-underscore-to-camel-case: true
